const translations = {
    ar: {
        title: "لوحة التحكم - مكتب المحاماة بالقدس",
        sidebarTitle: "⚖️ جسر القدس",
        btnLeads: "📋 طلبات الموكلين الجدد",
        btnArchive: "👥 الأرشيف والعملاء",
        btnSettings: "⚙️ إعدادات النظام",
        leadsSectionTitle: "إدارة طلبات إصابات العمل الواردة",
        archiveSectionTitle: "أرشيف العملاء المعالجة قضاياهم",
        settingsSectionTitle: "إعدادات نظام جسر القدس القانوني",
        settingsHeading: "🛠️ تفريغ الأرشيف والبيانات المعالجة",
        settingsDesc: "يمكنك مسح وتفريغ أرشيف الموكلين الذين تمت معالجتهم بالفعل للتنظيف، مع الحفاظ على كافة الطلبات الجديدة المعلقة دون تعديل:",
        resetBtn: "⚠️ تفريغ الأرشيف والعملاء المعالجة قضاياهم",
        resetConfirm: "⚠️ هل أنت متأكد من رغبتك في تفريغ الأرشيف ومسح كافة العملاء المعالجة قضاياهم؟ لن يتأثر موقع طلبات الموكلين الجدد نهائياً.",
        resetSuccess: "تم تفريغ الأرشيف والعملاء المعالجة قضاياهم بنجاح!",
        modalTitle: "📋 تفاصيل طلب الموكل",
        emptyLeads: "لا توجد طلبات جديدة معلقة. جميع الحالات تمت معالجتها!",
        emptyArchive: "الأرشيف فارغ حالياً.",
        colName: "الاسم",
        colPhone: "الهاتف",
        colCategory: "نوع الحادث / موقع العمل",
        colProcessed: "تمت المعالجة",
        colSummary: "ملخص الحادث",
        colAction: "الإجراء",
        btnDetails: "فتح التفاصيل",
        colArchiveStatus: "حالة الأرشفة",
        
        mName: "👤 اسم الموكل:",
        mPhone: "📞 رقم الهاتف:",
        mDate: "📅 تاريخ التقديم:",
        mLoc: "🏢 مكان الحادث والقانون:",
        mCat: "🛠️ نوع الحادث:",
        mNeg: "🚗 هل تعتقد بوجود طرف مسؤول؟",
        mBefore: "📍 أين كان الموكل قبل الإصابة؟",
        mStatus: "✔️ حالة المعالجة والمتابعة:",
        statusProcessed: "تمت معالجته وأرشفته",
        statusPending: "معلّق / لم تتم معالجته بعد",
        mFullDesc: "📝 النص الكامل لشرح الحادث:",
        mAiSummary: "💡 ملخص القضية لدراسة المحامي (AI Summary):",
        mAiText: (cat, loc, neg, before, details) => `طلب استشارة بخصوص (<strong>${cat}</strong>) وقع في (<strong>${loc}</strong>). المسؤولية: (<strong>${neg}</strong>). الموقع المسبق للموكل: (<strong>${before}</strong>). شرح الحادث: (<strong>${details}</strong>). الملف جاهز للتواصل المباشر مع العميل لإعداد المطالبة.`
    },
    he: {
        title: "לוח בקרה - משרד עורכי דין ירושלים",
        sidebarTitle: "⚖️ גשר אל-קודס",
        btnLeads: "📋 פניות לקוחות חדשות",
        btnArchive: "👥 ארכיון ולקוחות",
        btnSettings: "⚙️ הגדרות מערכת",
        leadsSectionTitle: "ניהול פניות ואינטייק מלקוחות",
        archiveSectionTitle: "ארכיון פניות מטופלות",
        settingsSectionTitle: "הגדרות מערכת גשר אל-קודס",
        settingsHeading: "🛠️ ניקוי ארכיון ונתונים",
        settingsDesc: "ניתן לרוקן את ארכיון הלקוחות שטופלו בלבד לצורך ניקוי המערכת, תוך שמירה על כל הפניות החדשות הממתינות ללא שינוי:",
        resetBtn: "⚠️ ריקון הארכיון ולקוחות מטופלים",
        resetConfirm: "⚠️ האם אתה בטוח שברצונך לרוקן את הארכיון? פעולה זו תמחק רק פניות מטופלות ולא תשפיע על פניות חדשות.",
        resetSuccess: "הארכיון ופניות מטופלות רוקנו בהצלחה!",
        modalTitle: "📋 פרטי פניית הלקוח",
        emptyLeads: "אין פניות חדשות ממתינות. כל המקרים טופלו בהצלחה!",
        emptyArchive: "הארכיון ריק כעת.",
        colName: "שם",
        colPhone: "טלפון",
        colCategory: "סוג התאונה / מיקום",
        colProcessed: "טופל",
        colSummary: "תקציר התאונה",
        colAction: "פעולה",
        btnDetails: "פרטים מלאים",
        colArchiveStatus: "סטטוס ארכוב",
        
        mName: "👤 שם הלקוח:",
        mPhone: "📞 מספר טלפון:",
        mDate: "📅 תאריך שליחה:",
        mLoc: "🏢 מיקום התאונה וסמכות שיפוט:",
        mCat: "🛠️ סוג התאונה:",
        mNeg: "🚗 האם קיים צד ג' אחראי?",
        mBefore: "📍 היכן היה הלקוח לפני התאונה?",
        mStatus: "✔️ סטטוס טיפול ומעקב:",
        statusProcessed: "טופל ואורכב במערכת",
        statusPending: "ממתין לטיפול / חדש",
        mFullDesc: "📝 פירוט האירוע המלא:",
        mAiSummary: "💡 סיכום תיק ראשוני לניתוח עורך דין (AI Summary):",
        mAiText: (cat, loc, neg, before, details) => `בקשת ייעוץ בנושא (<strong>${cat}</strong>) שהתרחשה ב(<strong>${loc}</strong>). אחריות צד ג': (<strong>${neg}</strong>). מיקום לפני התאונה: (<strong>${before}</strong>). פירוט האירוע: (<strong>${details}</strong>). התיק מוכן ליצירת קשר ראשוני עם הלקוח להכנת התביעה.`
    },
    en: {
        title: "Lawyer Dashboard - Jerusalem Law Firm",
        sidebarTitle: "⚖️ Al-Quds Law",
        btnLeads: "📋 New Client Submissions",
        btnArchive: "👥 Archive & Clients",
        btnSettings: "⚙️ System Settings",
        leadsSectionTitle: "Manage Incoming Case Submissions",
        archiveSectionTitle: "Archived Case Submissions",
        settingsSectionTitle: "JLM Legal Bridge System Settings",
        settingsHeading: "🛠️ Archive Cleanup & Data Management",
        settingsDesc: "You can clear the archive of processed client cases to clean up the system, while keeping all new pending submissions intact:",
        resetBtn: "⚠️ Clear Archive & Processed Clients",
        resetConfirm: "⚠️ Are you sure you want to clear the archive? This will only delete processed/archived client cases and keep all new pending submissions intact.",
        resetSuccess: "Archive cleared successfully! Processed cases removed.",
        modalTitle: "📋 Client Submission Details",
        emptyLeads: "No pending submissions. All cases are processed!",
        emptyArchive: "The archive is currently empty.",
        colName: "Name",
        colPhone: "Phone",
        colCategory: "Incident Type / Location",
        colProcessed: "Processed",
        colSummary: "Accident Summary",
        colAction: "Action",
        btnDetails: "Open Details",
        colArchiveStatus: "Archive Status",
        
        mName: "👤 Client Name:",
        mPhone: "📞 Phone Number:",
        mDate: "📅 Submission Date:",
        mLoc: "🏢 Accident Location & Jurisdiction:",
        mCat: "🛠️ Incident Category:",
        mNeg: "🚗 Is there a responsible third party?",
        mBefore: "📍 Client Location before incident:",
        mStatus: "✔️ Handling & Follow-up Status:",
        statusProcessed: "Processed & Archived",
        statusPending: "Pending / Unprocessed",
        mFullDesc: "📝 Full Accident Details Description:",
        mAiSummary: "💡 Case Summary for Attorney Review (AI Summary):",
        mAiText: (cat, loc, neg, before, details) => `Consultation request regarding (<strong>${cat}</strong>) occurred in (<strong>${loc}</strong>). Third-party liability: (<strong>${neg}</strong>). Pre-incident location: (<strong>${before}</strong>). Accident description: (<strong>${details}</strong>). File ready for direct client outreach.`
    }
};