/**
 * 🌐 client_lang.js - Client Intake Translation Schema
 * Unified dictionary of translations for Landing Page, Chatbot, Welcome Modal, and Appointment Booking.
 */
const translations = {
    ar: {
        title: "⚖️ جسر القدس القانوني",
        explainTitle: "🛡️ اشرحها لي ببساطة (كل ما تحتاج لمعرفته)",
        explainSub: "نجيب على مخاوفك الأساسية بوضوح تام ودون تعقيدات قانونية",
        costTitle: "💰 تكلفة الخدمة",
        costText: "🆓 الاستشارة الأولية مجانية 100%<br>📍 تتم عن بُعد بسهولة تامة",
        humanTitle: "🤝 المعاملة الإنسانية",
        humanText: "<strong>ودودون ونهتم بصحتك أولاً</strong>. نحن نسمعك ونحترم مشاعرك. لا يوجد أي ضغط عليك، ولك كامل الحرية في التراجع في أي لحظة.",
        paperTitle: "📁 البيروقراطية والأوراق",
        paperText: "<strong>نحن نتابع كل شيء</strong>. نتولى عنك سحب التقارير الطبية والمراسلات مع شركات التأمين ومؤسسات التأمين الوطني لتخفيف الجهد عليك.",
        roadmapTitle: "🗺️ خريطة الطريق لتعويضك",
        step1Label: "تقييم ذكي",
        step1Desc: "استبيان بسيط يستغرق دقيقتين لتحديد قوة قضيتك مجاناً.",
        step2Label: "دراسة ملفك",
        step2Desc: "يقوم مستشارنا الطبي والقانوني بمراجعة التقارير خلال أسبوع.",
        step3Label: "تقديم المطالبة",
        step3Desc: "مراسلة الجهات المقصرة ومؤسسات التأمين لبدء التفاوض.",
        step4Label: "استلام التعويض",
        step4Desc: "معظم القضايا تنتهي بتسوية مرضية خلال 6 إلى 12 شهر.",
        privacyText: "🔒 التزام السرية وحماية الخصوصية",
        heroTitle: "هل لديك تعويض بعد إصابة؟",
        heroSubtitle: "اكتشف خلال دقيقة مجاناً",
        startBtn: "👉 ابدأ الآن",
        welcomeMsg: "مرحبًا بك، سأطرح عليك بعض الأسئلة البسيطة لفهم حالتك وتقييم إمكانية حصولك على تعويض مالي.",
        q1Title: "<strong>ما هو نوع الحادث الذي تعرضت له؟</strong><br><small style='color: var(--accent-gold);'>* هذا يساعدنا على تحديد نوع الحادث الذي تعرضت له</small>",
        q1OptTraffic: "🚗 حادث سير / مرور",
        q1OptWork: "🛠️ إصابة عمل / مصنع",
        q1OptOther: "⚠️ سقوط في مكان عام / أخرى",
        q2Title: "<strong>أين وقع الحادث تحديداً؟</strong><br><small style='color: var(--accent-gold);'>* هذا يساعدنا على تحديد القانون المطبق (قانون إسرائيلي أم فلسطيني في تلك المنطقة).</small>",
        q2OptWB: "📍 منطقة الضفة الغربية (قانون فلسطيني)",
        q2OptIL: "📍 منطقة إسرائيلية (قانون إسرائيلي)",
        q3Title: "<strong>هل تعتقد أن هناك طرف مسؤول عن إصابتك؟</strong>",
        q3OptYes: "نعم، أعتقد أن هناك طرف آخر يجب أن يتحمل المسؤولية",
        q3OptSure: "غير متأكد (أرجو أن تساعدوني)",
        q3OptOther: "سبب آخر",
        q4Title: "<strong>اشرح لي باختصار ما الذي حدث معك؟</strong><br><small style='color: var(--accent-gold);'>* ليتمكن مكتب المحاماه من فهم تفاصيل الحادث وسياقه.</small>",
        q5Title: "<strong>أين كنت قبل أن تتعرض للإصابة؟</strong><br><small style='color: var(--accent-gold);'>* يساعدنا في بناء سياق الحادث وفهم الحالة</small>",
        q6Yes: "✅ <strong>بناءً على معلوماتك، يبدو أن لديك حالة محتملة للحصول على تعويض مالي.</strong>",
        q6No: "⚠️ <strong>بناءً على معلوماتك، قد تكون هناك فرصة للمطالبة بتعويضات جزئية أو عبر التأمين الوطني.</strong>",
        q6Permission: "<strong>للبدء في مراجعة حالتك، يجب ان توافق على مشاركة هذه التفاصيل المبدئية بشكل آمن وسري إلى مكتب المحاماة ليتواصل معك مستشارنا خلال هذا الأسبوع؟</strong><br><br><small style='color: var(--accent-gold); line-height: 1.5; display: block;'>🆓 المراجعة مجانية تماماً وبدون أي التزام عليك.<br>💰 لا توجد أي تكلفة مسبقة أو رسوم خفية (0 ₪).<br>🔒 سرية تامة ومحمية بالكامل.</small>",
        q6OptAgree: "نعم، أوافق على التواصل وإرسال التفاصيل",
        q6OptDecline: "لا، أريد إغلاق المحادثة وحذف بياناتي للسرية التامة",
        q6Undo: "🔄 تراجع",
        q6Closed: "❌ تم إغلاق المحادثة وتدمير كافة البيانات فوراً لحماية خصوصيتك التامة.",
        q7Contact: "<strong>يرجى إدخال تفاصيل الاتصال بك لإتمام إرسال الملف لمكتب المحامي:</strong>",
        q7Name: "اسمك الكريم",
        q7Phone: "رقم هاتفك المحمول (10 أرقام، مثال: 0521234567)",
        q7Submit: "موافق",
        finalSuccess: "✅ <strong>تم إرسال حالتك بنجاح</strong><br><br>⏱️ سيتم مراجعتها من قبل مكتب المحاماه المختص خلال وقت قصير<br><br>✅ لا يوجد أي التزام عليك",
        micTitle: "🎙️ اختر لغة التحدث:",
        micStop: "⏹️ إيقاف وتأكيد الصوت",
        micCancel: "❌ إلغاء",
        q4Placeholder: "(اختياري) اكتب هنا أو تحدث عبر الميكروفون...",
        q5Placeholder: "(اختياري) اكتب هنا أو تحدث عبر الميكروفون...",
        q7Alert: "يرجى إدخال الاسم ورقم الهاتف.",
        q7PhoneAlert: "يرجى إدخال رقم هاتف محمول صحيح يتكون من 10 أرقام ويبدأ بـ 05 (مثال: 0521234567).",
        servicesModalTitle: "⚖️ من نحن - مكتب جسر القدس للمحاماة",
        servicesModalContent: "<p>📍 <strong>مكتب رسمي معتمد في مدينة القدس</strong> يقدم خدمات الدفاع والمطالبة القانونية لشرائح المجتمع المقدسي:</p><p>من أبرز مجالات عمل المكتب:</p><p>🔹 <strong>الاستشارات الطبية-القانونية:</strong> مراجعة التقارير الطبية للموكلين عبر أطباء المكتب المعتمدين لتجهيز ملف دعوى متكامل وقوي.</p><p>🔹 <strong>حوادث السير والطرق:</strong> تحصيل أقصى تعويضات مالية ممكنة للمصابين طبقاً لقانون التعويضات.</p><p>🔹 <strong>إصابات العمل بالمصانع والورش:</strong> مراجعة القضايا أمام مؤسسة التأمين الوطني (بيטוח לאומי) وتثبيت نسب العجز الطبي.</p><details class='services-expandable-card'><summary>💼 هل تبحث عن خدمات قانونية أخرى؟ انقر للاستعراض ▾</summary><div class='services-expandable-grid'><div class='grid-service-item'><span>⚖️</span>القضايا المدنية</div><div class='grid-service-item'><span>👨‍👩‍👧‍👦</span>الأحوال الشخصية</div><div class='grid-service-item'><span>🏢</span>العقارات والأراضي</div><div class='grid-service-item'><span>💼</span>قضايا العمل</div><div class='grid-service-item'><span>🛡️</span>قضايا التأمين</div><div class='grid-service-item'><span>🏛️</span>القضايا الجنائية</div></div></details>",
        privacyModalTitle: "🔒 التزام السرية وحماية الخصوصية",
        privacyModalContent: "<p>نحن في مكتب القدس نلتزم بأعلى درجات السرية المهنية لحماية حقوق موكلينا المصابين:</p><p>🔐 **حفظ البيانات محلياً:** إجاباتك وتعليقاتك أثناء المحادثة تُخزن مؤقتاً وبشكل آمن على متصفحك وجهازك فقط.</p><p>🛡️ **التحكم المطلق لك:** لن يتم إرسال أي معلومة أو ملف للمكتب بدون ضغطك الصريح على زر الموافقة في نهاية الدردشة.</p><p>❌ **حق تدمير البيانات:** إذا اخترت عدم إرسال الطلب وإغلاق الشات، يتم مسح وتدمير كافة بيانات الجلسة فوراً دون الإبقاء على أي أثر لها.</p>",
        footerCopyright: "© 2026 مكتب جسر القدس للمحاماة والاستشارات القانونية. جميع الحقوق محفوظة.",
        linkServices: "من نحن",
        linkPrivacy: "الخصوصية",
        footerServices: "من نحن",
        footerPrivacy: "الخصوصية",
        faqTitle: "💬 الأسئلة الشائعة وتجارب الموكلين",
        faq1Q: "❓ كيف يتم تحديد قيمة التعويض المالي؟",
        faq1A: "تعتمد القيمة على طبيعة الحادث، التقارير الطبية، ونسبة العجز المقدرة من الجهات المختصة مثل التأمين الوطني.",
        faq2Q: "❓ هل التقييم الذكي يلزمني بأي شيء؟",
        faq2A: "أبداً. التقييم سري تماماً ويتم على متصفحك. لن تتم مشاركة أي معلومة إلا إذا اخترت بنفسك في نهاية المطاف إرسالها ومتابعة العمل معنا.",
        bioTitle: "مكتب جسر القدس القانوني",
        bioSubtitle: "مستشارك الإنساني والقانوني المعتمد",
        bioQuote: "\"حقك المالي ليس طمعاً، بل هو تعويض عادل لمساعدتك على استعادة حياتك وصحتك. شركات التأمين تعتمد دائماً على تأجيلك للمطالبة حتى يسقط حقك بالتقادم. نحن هنا لنسمعك ونسانك خطوة بخطوة.\"",
        chatBadge: "استشارة أولية مجانية",
        backToHomeBtn: "⬅️ رجوع",
        
        // Welcome Modal Keys
        wTitle: "أهلاً بك في جسر القدس القانوني",
        wSpec: "⚖️ يختص مكتبنا في قضايا التعويضات وإصابات العمل وحوادث الطرق وغيرها من الاصابات",
        wWhatTitle: "ماذا يمكنك أن تفعل من خلال الموقع؟",
        wOpt1: "✅ الحصول على استشارة أولية عن بُعد مجاناً.",
        wOpt2: "✅ معرفة ما إذا كانت حالتك قد تستحق تعويضاً مالياً.",
        wOpt3: "✅ إرسال تفاصيل حالتك للمراجعة من قبل مكتب المحامي مختص.",
        wOpt4: "✅ طلب مكالمة هاتفية أو حجز موعد في المكتب.",
        wBeforeTitle: "قبل أن تبدأ:",
        wBeforeDesc: "سيقوم المساعد الذكي بطرح مجموعة من الأسئلة البسيطة لفهم حالتك بشكل أولي. تستغرق العملية عادة أقل من دقيقتين.",
        wPrivacy: "🔒 معلوماتك تُعامل بسرية تامة.",
        wCloseBtn: "شكراً، فهمت",

        // Appointment Booking Keys
        appLinkText: "حجز موعد",
        appModalTitle: "📅 طلب حجز موعد جديد",
        appSelectDate: "اختر التاريخ المفضل:",
        appSelectTime: "اختر وقت الحجز المتاح:",
        appClientName: "الاسم الكريم:",
        appClientPhone: "رقم الهاتف المحمول:",
        appClientNotes: "خيارات لاختيار صنف القضية:",
        appBtnSubmit: "تأكيد طلب الموعد",
        appBtnCancelClose: "إلغاء وإغلاق",
        appSuccessToast: "🎉 تم إرسال طلب حجز الموعد بنجاح. سنتواصل معك لتأكيده!",
        appAlertDate: "يرجى تحديد التاريخ المفضل.",
        appAlertTime: "يرجى تحديد الوقت المفضل للموعد.",
        appAlertName: "يرجى إدخال اسمك الكريم.",
        appAlertPhone: "يرجى إدخال رقم هاتف محمول صحيح يتكون من 10 أرقام ويبدأ بـ 05.",
        appSelectPlaceholder: "-- يرجى اختيار صنف القضية --",
        appAlertCategory: "يرجى اختيار صنف القضية من القائمة المتاحة.",
        appCaseOptions: [
            "قضايا حوادث السير: (حوادث المركبات، الدهس، التأمين، التعويضات والوفاة)",
            "قضايا الإصابات: (الإصابات الشخصية، إصابات العمل، الأخطاء الطبية، العجز والتعويض)",
            "القضايا المدنية: (النزاعات المالية، العقود، التعويض عن الأضرار، الملكية والعقارات)",
            "القضايا الجنائية (الجزائية): (السرقة، الاحتيال، الاعتداء، الجرائم الإلكترونية، المخدرات)",
            "قضايا الأحوال الشخصية (الأسرة): (الزواج، الطلاق، النفقة، الحضانة، الميراث والوصايا)",
            "القضايا العمالية: (حقوق العمل، الفصل، الأجور والتعويضات)",
            "القضايا التجارية: (النزاعات، الشركات، الأوراق التجارية، الإفلاس والعقود)",
            "القضايا الإدارية: (الطعون في القرارات الحكومية والمنازعات العامة)",
            "القضايا العقارية: (الملكية، الإيجارات، تسجيل الأراضي والحدود)"
        ],
        badge1: "✅ بدون تكلفة",
        badge2: "✅ بدون التزام",
        badge3: "✅ خلال دقيقتين فقط"
    },
    he: {
        title: "⚖️ משרד עורכי דין גשר אל-קודס",
        explainTitle: "🛡️ הסבר פשוט (כל מה שצריך לדעת)",
        explainSub: "אנו עונים על החששות העיקריים שלך בבירור וללא סיבוכים משפטיים",
        costTitle: "💰 עלות השירות",
        costText: "🆓 הייעוץ הראשוני הוא 100% בחינם<br>📍 מתבצע מרחוק בנוחות מלאה",
        humanTitle: "🤝 יחס אנושי וחם",
        humanText: "<strong>ידידותיים ודואגים לבריאות שלך קודם כל</strong>. אנו מקשיבים לך ומכבדים את הרגשות שלך. אין עליך שום לחץ, ויש לך חופש מלא לחזור בך בכל רגע.",
        paperTitle: "📁 בירוקרטיה וניירת",
        paperText: "<strong>אנו מטפלים בהכל</strong>. אנו דואגים למשוך עבורך את הדוחות הרפואיים ולנהל את התכתובות מול חברות הביטוח והביטוח הלאומי כדי להקל עליך.",
        roadmapTitle: "🗺️ מפת הדרכים לפיצוי שלך",
        step1Label: "הערכה חכמה",
        step1Desc: "שאלון פשוט של 2 דקות לקביעת חוזק התיק שלך בחינם.",
        step2Label: "دراسة ملفك",
        step2Desc: "היועץ המשפטי שלנו יצור איתך קשר כדי להסביר את הצעדים הבאים.",
        step3Label: "تقديم المطالبة",
        step3Desc: "אנו אוספים את הדוחות הרפואיים והראיות כדי לבסס תביעה חזקה.",
        step4Label: "קבלת הפיצוי",
        step4Desc: "אנו נלחמים בבתי המשפט ומול חברות הביטוח כדי להבטיח לך את הפיצוי המקסימלי.",
        privacyText: "🔒 מחויבות לסודיות והגנה על הפרטיות",
        heroTitle: "עברת תאונת דרכים או נפצעת בעבודה?",
        heroSubtitle: "אל תוותר על הזכויות הכספיות שלך. קבל הערכה מיידית לתיק שלך ודע מה שווי הפיצויים הפוטנציאליים איתנו.",
        startBtn: "👉 התחל עכשיו",
        welcomeMsg: "ברוך הבא, אשאל אותך כמה שאלות פשוטות כדי להבין את מצבך ולהעריך את האפשרות לקבלת פיצוי כספי.",
        q1Title: "<strong>מהו סוג התאונה שעברת?</strong><br><small style='color: var(--accent-gold);'>* זה עוזר לנו לקבוע את סוג התאונה שעברת</small>",
        q1OptTraffic: "🚗 תאונת דרכים / תנועה",
        q1OptWork: "🛠️ תאונת עבודה / מפעל",
        q1OptOther: "⚠️ נפילה במקום ציבורי / אחר",
        q2Title: "<strong>איפה בדיוק קרתה התאונה?</strong><br><small style='color: var(--accent-gold);'>* זה עוזר לנו לקבוע את החוק החל (חוק ישראלי או פלסטיני באותו אזור).</small>",
        q2OptWB: "📍 אזור הגדה המערבית (חוק פלסטיני)",
        q2OptIL: "📍 אזור ישראלי (חוק ישראלי)",
        q3Title: "<strong>האם אתה חושב שיש גורם האחראי לפציעתך?</strong>",
        q3OptYes: "כן, אני חושב שיש גורם אחר שצריך לשאת באחריות",
        q3OptSure: "לא בטוח (אנא עזרו לי)",
        q3OptOther: "סיבה אחרת",
        q4Title: "<strong>הסבר לי בקצרה מה קרה לך?</strong><br><small style='color: var(--accent-gold);'>* כדי שמשרד עורכי הדין יוכל להבין את פרטי התאונה והקשרה.</small>",
        q5Title: "<strong>איפה היית לפני שנפצעת?</strong><br><small style='color: var(--accent-gold);'>* עוזר לנו לבנות את הקשר התאונה ולהבין את המצב</small>",
        q6Yes: "✅ <strong>לפי המידע שמסרת, נראה שיש לך עילה פוטנציאלית לקבלת פיצוי כספי.</strong>",
        q6No: "⚠️ <strong>לפי המידע שמסרת, ייתכן שיש הזדמנות לתביעת פיצויים חלקיים או דרך הביטוח הלאומי.</strong>",
        q6Permission: "<strong>כדי להתחיל בבדיקת מצבך, האם אתה מסכים לשתף פרטים ראשוניים אלו באופן מאובטח וסודי עם משרד עורכי הדין על מנת שהיועץ שלנו יצור איתך קשר השבוע?</strong><br><br><small style='color: var(--accent-gold); line-height: 1.5; display: block;'>🆓 הבדיקה היא 100% בחינם וללא כל התחייבות מצדך.<br>💰 אין שום עלות מראש או עמלות נסתרות (0 ₪).<br>🔒 סודיות מלאה ומאובטחת לחלוטין.</small>",
        q6OptAgree: "כן, אני מסכים ליצירת קשר ושליחת הפרטים",
        q6OptDecline: "לא, אני רוצה לסגור את השיחה ולמחוק את הנתונים שלי לפרטיות מלאה",
        q6Undo: "🔄 ביטול",
        q6Closed: "❌ השיחה נסגרה וכל הנתונים נמחקו מיידית להגנה מלאה על הפרטיות שלך.",
        q7Contact: "<strong>אנא הזן את פרטי הקשר שלך להשלמת שליחת התיק לעורך הדין:</strong>",
        q7Name: "שם מלא",
        q7Phone: "מספר טלפון נייד (10 ספרות, למשל: 0521234567)",
        q7Submit: "אישור",
        finalSuccess: "✅ <strong>הפרטים נשלחו בהצלחה</strong><br><br>⏱️ התיק ייבדק על ידי עורך דין מומחה תוך זמן קצר<br><br>✅ ללא כל התחייבות מצדך",
        micTitle: "🎙️ בחר שפת דיבור:",
        micStop: "⏹️ עצור ואשר קול",
        micCancel: "❌ ביטול",
        q4Placeholder: "(אופציונלי) כתוב כאן או דבר במיקרופון...",
        q5Placeholder: "(אופציונלי) כתוב כאן או דבר במיקרופון...",
        q7Alert: "אנא הזן את השם ומספר הטלפון.",
        q7PhoneAlert: "אנא הזן מספר טלפון נייד תקין בן 10 ספרות המתחיל ב-05 (למשל: 0521234567).",
        servicesModalTitle: "⚖️ מי אנחנו - משרד עורכי דין גשר אל-קודס",
        servicesModalContent: "<p>📍 <strong>משרד רשמי מוסמך בירושלים</strong> המספק שירותי הגנה ותביעות משפטיות לכלל האוכלוסייה:</p><p>תחומי הפעילות העיקריים של המשרד:</p><p>🔹 <strong>ייעוץ רפואי-משפטי:</strong> סקירת דוחות רפואיים של לקוחות באמצעות רופאי המשרד המוסמכים להכנת תיק תביעה חזק ומלא.</p><p>🔹 <strong>תאונות דרכים ותנועה:</strong> השגת פיצויים כספיים מקסימליים לנפגעים על פי חוק הפיצויים.</p><p>🔹 <strong>תאונות עבודה במפעלים ובתי מלאכה:</strong> ניהול תביעות מול המוסד לביטוח לאומי וקביעת אחוזי נכות רפואית.</p><details class='services-expandable-card'><summary>💼 מחפש שירותים משפטיים נוספים? לחץ לצפייה ▾</summary><div class='services-expandable-grid'><div class='grid-service-item'><span>⚖️</span>משפט אזרחי</div><div class='grid-service-item'><span>👨‍👩‍👧‍👦</span>מעמד אישי ומשפחה</div><div class='grid-service-item'><span>🏢</span>מקרקעין ונדל\"ן</div><div class='grid-service-item'><span>💼</span>דיני עבודה</div><div class='grid-service-item'><span>🛡️</span>דיני ביטוח ותביעות</div><div class='grid-service-item'><span>🏛️</span>משפט פלילי</div></div></details>",
        privacyModalTitle: "🔒 מחויבות לסודיות והגנה על הפרטיות",
        privacyModalContent: "<p>אנו במשרד גשר אל-קודס מחויבים לרמה הגבוהה ביותר של סודיות מקצועית כדי להגן על זכויות לקוחותינו הנפגעים:</p><p>🔐 **שמירת נתונים מקומית:** התשובות וההערות שלך במהלך השיחה נשמרות באופן זמני ומאובטח בדפדפן ובמכשיר שלך בלבד.</p><p>🛡️ **שליטה מוחלטת שלך:** שום מידע או קובץ לא יישלחו למשרד ללא אישורך המפורש בלחיצה על כפתור השליחה בסוף השיחה.</p><p>❌ **הזכות למחיקת נתונים:** אם תבחר שלא לשלוח את התביעה ולסגור את השיחה, כל נתוני השיחה יימחקו ויושמדו מיידית ללא השארת עקבות.</p>",
        footerCopyright: "© 2026 משרד עורכי דין גשר אל-קודס. כל הזכויות שמורות.",
        linkServices: "מי אנחנו",
        linkPrivacy: "מדיניות פרטיות",
        footerServices: "מי אנחנו",
        footerPrivacy: "מדיניות פרטיות",
        faqTitle: "💬 שאלות נפוצות וחוויות לקוחות",
        faq1Q: "❓ כיצד נקבע גובה הפיצוי הכספי?",
        faq1A: "הגובה נקבע על פי אופי התאונה, הדוחות הרפואיים ואחוזי הנכות המוערכים על ידי הרשויות המוסמכות כגון הביטוח הלאומי.",
        faq2Q: "❓ האם ההערכה החכמה מחייבת אותי במשהו?",
        faq2A: "בכלל לא. ההערכה היא סודית לחלוטין ומתבצעת בדפדפן שלך. שום מידע לא ישותף אלא אם תבחר בעצמך בסופו של דבר לשלוח אותו ולהמשיך לעבוד איתנו.",
        bioTitle: "משרד עורכי דין גשר אל-קודס",
        bioSubtitle: "היועץ האנושי והמשפטי המוסמך שלך",
        bioQuote: "\"הזכות הכספית שלך אינה חמדנות, אלא פיצוי הוגן שיעזור לך לשקם את חייך ובריאותך. חברות הביטוח מסתמכות תמיד על כך שתדחה את התביעה עד שתפוג תקופת ההתיישנות. אנו כאן כדי להקשיב ולתמוך בך צעד אחר צעד.\"",
        chatBadge: "ייעוץ ראשוני חינם",
        backToHomeBtn: "⬅️ חזרה",

        // Welcome Modal Keys
        wTitle: "ברוכים הבאים לגשר אל-קודס המשפטי",
        wSpec: "⚖️ משרדנו מתמחה בתביעות פיצויים, תאונות עבודה ותאונות דרכים",
        wWhatTitle: "מה ניתן לעשות באמצעות האתר?",
        wOpt1: "✅ קבלת ייעוץ ראשוני מרחוק ללא עלות.",
        wOpt2: "✅ בדיקה האם המקרה שלך עשוי להקנות לך פיצוי כספי.",
        wOpt3: "✅ שליחת פרטי המקרה לבדיקה על ידי עורך דין מומחה.",
        wOpt4: "✅ בקשת שיחת טלפון או קביעת פגישה במשרד.",
        wBeforeTitle: "לפני שמתחילים:",
        wBeforeDesc: "העוזר החכם ישאל אותך מספר שאלות פשוטות כדי להבין את המקרה שלך באופן ראשוני. התהליך לוקח פחות משתי דקות.",
        wPrivacy: "🔒 המידע שלך מטופל בסודיות מוחלטת.",
        wCloseBtn: "תודה, הבנתי",

        // Appointment Booking Keys
        appLinkText: "קביעת תור",
        appModalTitle: "📅 בקשת קביעת תור חדש",
        appSelectDate: "בחר תאריך מועדף:",
        appSelectTime: "בחר שעה פנויה:",
        appClientName: "שם מלא:",
        appClientPhone: "מספר טלפון נייד:",
        appClientNotes: "אפשרויות לבחירת סוג התיק:",
        appBtnSubmit: "אישור בקשת תור",
        appBtnCancelClose: "ביטול וסגירה",
        appSuccessToast: "🎉 בקשת התור נשלחה בהצלחה! ניצור איתך קשר בהקדם.",
        appAlertDate: "נא לבחור תאריך לתור.",
        appAlertTime: "נא לבחור שעה מועדפת לתור.",
        appAlertName: "נא להזין שם מלא.",
        appAlertPhone: "נא להזין מספר טלפון נייד תקין בן 10 ספרות המתחיל ב-05.",
        appSelectPlaceholder: "-- נא לבחור סוג פנייה --",
        appAlertCategory: "נא לבחור את סוג התיק מהרשימה.",
        appCaseOptions: [
            "תביעות תאונות דרכים: (תאונות רכב, דריסה, ביטוח, נזקי גוף ומוות)",
            "תביעות נזקי גוף ופציעות: (פציעות אישיות, תאונות עבודה, רשלנות רפואית, נכות ופיצויים)",
            "תיקים אזרחיים: (סכסוכים כספיים, חוזים, פיצוי בגין נזקים, בעלות ומקרקעין)",
            "תיקים פליליים: (גניבה, מרמה, תקיפה, פשעי סייבר, עבירות סמים)",
            "מעמד אישי ומשפחה: (גירושין, מזונות, משמורת ילדים, ירושות וצוואות)",
            "דיני עבודה: (זכויות עובדים, פיטורין, שכר ופיצויים)",
            "תיקים מסחריים: (סכסוכים, חברות, מסמכים סחירים, פשיטת רגל וחוזים)",
            "תיקים מנהליים: (ערעור על החלטות ממשלה, סכסוכים עם גופים ציבוריים)",
            "תיקי מקרקעין ונדל\"ן: (בעלות, שכירות, רישום מקרקעין וגבולות)"
        ],
        badge1: "✅ ללא עלות",
        badge2: "✅ ללא התחייבות",
        badge3: "✅ תוך 2 דקות בלבד"
    },
    en: {
        title: "⚖️ Al-Quds Law Firm",
        explainTitle: "🛡️ Explain it Simply (Everything you need to know)",
        explainSub: "We answer your primary concerns clearly and without legal jargon",
        costTitle: "💰 Cost of Service",
        costText: "🆓 Initial consultation is 100% free<br>📍 Done fully remotely with ease",
        humanTitle: "🤝 Human Treatment",
        humanText: "<strong>Friendly and health-first approach</strong>. We listen to you and respect your feelings. There is absolutely no pressure, and you have full freedom to opt out at any time.",
        paperTitle: "📁 Bureaucracy & Paperwork",
        paperText: "<strong>We follow up on everything</strong>. We handle retrieving medical reports and communicating with insurance companies and national insurance to relieve your burden.",
        roadmapTitle: "🗺️ Roadmap to Your Compensation",
        step1Label: "Smart Evaluation",
        step1Desc: "A simple 2-minute questionnaire to determine the strength of your case for free.",
        step2Label: "Study File",
        step2Desc: "Our legal advisor contacts you to clarify your next steps.",
        step3Label: "File Claim",
        step3Desc: "We gather medical reports and evidence to establish a strong claim.",
        step4Label: "Claim Settlement",
        step4Desc: "We fight in courts and with insurance companies to secure your maximum financial compensation.",
        privacyText: "🔒 Commitment to Secrecy & Privacy Protection",
        heroTitle: "Were you in a road accident or injured at work?",
        heroSubtitle: "Do not lose your financial rights. Get an instant evaluation of your case and know your potential compensation with us.",
        startBtn: "👉 Start Now",
        welcomeMsg: "Welcome, I will ask you a few simple questions to understand your situation and evaluate your eligibility for financial compensation.",
        q1Title: "<strong>What type of accident did you experience?</strong><br><small style='color: var(--accent-gold);'>* This helps us identify the type of claim</small>",
        q1OptTraffic: "🚗 Road / Traffic Accident",
        q1OptWork: "🛠️ Work / Factory Injury",
        q1OptOther: "⚠️ Fall in a Public Place / Other",
        q2Title: "<strong>Where exactly did the accident occur?</strong><br><small style='color: var(--accent-gold);'>* This helps us determine the applicable law (Israeli or Palestinian law in that region).</small>",
        q2OptWB: "📍 West Bank Area (Palestinian Law)",
        q2OptIL: "📍 Israeli Area (Israeli Law)",
        q3Title: "<strong>Do you think someone is responsible for your injury?</strong>",
        q3OptYes: "Yes, I believe another party should take responsibility",
        q3OptSure: "Not sure (please help me)",
        q3OptOther: "Other reason",
        q4Title: "<strong>Briefly explain what happened to you?</strong><br><small style='color: var(--accent-gold);'>* So the law firm can understand the accident details and context.</small>",
        q5Title: "<strong>Where were you before you got injured?</strong><br><small style='color: var(--accent-gold);'>* Helps us establish the context of the accident and understand the situation</small>",
        q6Yes: "✅ <strong>Based on your information, you seem to have a potential case for financial compensation.</strong>",
        q6No: "⚠️ <strong>Based on your information, there might be a chance for partial compensation or through National Insurance.</strong>",
        q6Permission: "<strong>To start reviewing your case, do you agree to share these initial details securely and confidentially with the law firm so our advisor can contact you this week?</strong><br><br><small style='color: var(--accent-gold); line-height: 1.5; display: block;'>🆓 The review is 100% free with no obligation.<br>💰 No upfront costs or hidden fees (0 ₪).<br>🔒 Fully secured and confidential.</small>",
        q6OptAgree: "Yes, I agree to be contacted and send details",
        q6OptDecline: "No, I want to close the chat and destroy my data for absolute privacy",
        q6Undo: "🔄 Undo",
        q6Closed: "❌ The chat is closed and all data has been destroyed immediately to protect your privacy.",
        q7Contact: "<strong>Please enter your contact details to complete sending the file to the lawyer:</strong>",
        q7Name: "Your Name",
        q7Phone: "Mobile Phone Number (10 digits, e.g., 0521234567)",
        q7Submit: "OK",
        finalSuccess: "✅ <strong>Details sent successfully</strong><br><br>⏱️ Your case will be reviewed by a specialist lawyer shortly<br><br>✅ No obligation on your part",
        micTitle: "🎙️ Choose speech language:",
        micStop: "⏹️ Stop & Confirm Speech",
        micCancel: "❌ Cancel",
        q4Placeholder: "(Optional) Write here or speak through the microphone...",
        q5Placeholder: "(Optional) Write here or speak through the microphone...",
        q7Alert: "Please enter your name and phone number.",
        q7PhoneAlert: "Please enter a valid mobile number starting with 05 (e.g., 0521234567).",
        servicesModalTitle: "⚖️ About Us - Jerusalem Legal Bridge",
        servicesModalContent: "<p>📍 <strong>Official certified office in Jerusalem</strong> providing legal defense and claim services to all sectors of the community:</p><p>Main areas of practice:</p><p>🔹 <strong>Road & Traffic Accidents:</strong> Securing maximum financial compensation for injured victims under the compensation law.</p><p>🔹 <strong>Work Injuries in Factories & Workshops:</strong> Managing claims before the National Insurance Institute (NII) and establishing medical disability rates.</p><p>🔹 <strong>Medico-Legal Consultations:</strong> Reviewing clients' medical reports via the firm's certified doctors to prepare a strong and complete lawsuit file.</p><details class='services-expandable-card'><summary>💼 Looking for other legal services? Click to expand ▾</summary><div class='services-expandable-grid'><div class='grid-service-item'><span>⚖️</span>Civil Law</div><div class='grid-service-item'><span>👨‍👩‍👧‍👦</span>Personal Status</div><div class='grid-service-item'><span>🏢</span>Real Estate & Land</div><div class='grid-service-item'><span>💼</span>Labor & Employment</div><div class='grid-service-item'><span>🛡️</span>Insurance Claims</div><div class='grid-service-item'><span>🏛️</span>Criminal Law</div></div></details>",
        privacyModalTitle: "🔒 Commitment to Secrecy & Privacy Protection",
        privacyModalContent: "<p>We at Al-Quds Office commit to the highest levels of professional secrecy to protect the rights of our injured clients:</p><p>🔐 **Local Data Storage:** Your answers and comments during the chat are stored temporarily and securely on your browser and device only.</p><p>🛡️ **Absolute Control is Yours:** No info or file will be sent to the office without your explicit consent by clicking the submit button at the end of the chat.</p><p>❌ **Right to Destroy Data:** If you choose not to submit and close the chat, all session data is deleted and destroyed immediately without leaving any trace.</p>",
        footerCopyright: "© 2026 Al-Quds Law Firm. All rights reserved.",
        linkServices: "About Us",
        linkPrivacy: "Privacy Policy",
        footerServices: "About Us",
        footerPrivacy: "Privacy Policy",
        faqTitle: "💬 Frequently Asked Questions & Client Experiences",
        faq1Q: "❓ How is the financial compensation amount determined?",
        faq1A: "The amount depends on the nature of the accident, medical reports, and the disability percentage estimated by competent authorities such as National Insurance.",
        faq2Q: "❓ Does the smart evaluation commit me to anything?",
        faq2A: "Never. The evaluation is completely confidential and is done on your browser. No information will be shared unless you choose at the end to send it and follow up with us.",
        bioTitle: "Jerusalem Legal Bridge Law Firm",
        bioSubtitle: "Your Certified Human & Legal Advisor",
        bioQuote: "\"Your financial right is not greed, but a fair compensation to help you restore your life and health. Insurance companies always rely on you delaying the claim until it expires by statute of limitations. We are here to listen and support you step by step.\"",
        chatBadge: "Free Initial Consultation",
        backToHomeBtn: "⬅️ Back",

        // Welcome Modal Keys
        wTitle: "Welcome to Jerusalem Legal Bridge",
        wSpec: "⚖️ Our firm specializes in compensation, work injuries, and traffic accidents",
        wWhatTitle: "What can you do on this website?",
        wOpt1: "✅ Obtain a free initial remote consultation.",
        wOpt2: "✅ Learn if your case might be eligible for financial compensation.",
        wOpt3: "✅ Send your case details to the law firm for review by a specialist lawyer.",
        wOpt4: "✅ Request a callback or book an appointment at our office.",
        wBeforeTitle: "Before you start:",
        wBeforeDesc: "The smart assistant will ask simple questions to understand your case initially. The process takes less than 2 minutes.",
        wPrivacy: "🔒 Your information is treated with strict confidentiality.",
        wCloseBtn: "Thank you, I understand",

        // Appointment Booking Keys
        appLinkText: "Book Appointment",
        appModalTitle: "📅 Request New Appointment",
        appSelectDate: "Select Preferred Date:",
        appSelectTime: "Select Available Time Slot:",
        appClientName: "Full Name:",
        appClientPhone: "Mobile Phone Number:",
        appClientNotes: "Options to select the case category:",
        appBtnSubmit: "Confirm Appointment Request",
        appBtnCancelClose: "Cancel & Close",
        appSuccessToast: "🎉 Appointment request submitted successfully! We will contact you to confirm.",
        appAlertDate: "Please select your preferred date.",
        appAlertTime: "Please select your preferred time slot.",
        appAlertName: "Please enter your name.",
        appAlertPhone: "Please enter a valid 10-digit mobile number starting with 05.",
        appSelectPlaceholder: "-- Please Select Case Category --",
        appAlertCategory: "Please choose a case category from the dropdown.",
        appCaseOptions: [
            "Traffic Accidents: (Vehicle Accidents, Insurance, Injury & Fatal Claims)",
            "Injury Claims: (Personal Injury, Work Injuries, Medical Malpractice, Disability & Damages)",
            "Civil Cases: (Financial Disputes, Contracts, Damages, Property & Ownership)",
            "Criminal Cases: (Theft, Fraud, Assault, Cybercrimes, Drug Offenses)",
            "Family & Personal Status: (Marriage, Divorce, Alimony, Child Custody, Wills & Estate)",
            "Labor & Employment: (Employment Rights, Wrongful Dismissal, Wages & Compensation)",
            "Commercial Cases: (Disputes, Corporate, Commercial Papers, Bankruptcy & Contracts)",
            "Administrative Cases: (Appeals Against Government Decisions & Public Disputes)",
            "Real Estate Cases: (Property Ownership, Rentals, Land Registry & Boundaries)"
        ],
        badge1: "✅ Free of Cost",
        badge2: "✅ No Obligation",
        badge3: "✅ In 2 Minutes Only"
    }
};